# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:16-alpine # On utilise la version Alpine, ultra-légère (idéal pour le développement)
    container_name: stock_db
    restart: always
    environment:
      POSTGRES_USER: admin_stock
      POSTGRES_PASSWORD: superpassword123 # Mot de passe de dev
      POSTGRES_DB: stock_manager_db
    ports:
      - "5432:5432" # On mappe le port par défaut de PostgreSQL vers ton localhost
    volumes:
      - pgdata:/var/lib/postgresql/data # Persistance des données (le disque dur virtuel)
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Script d'auto-provisionnement au premier démarrage

volumes:
  pgdata: